apiVersion: v1
kind: Secret
metadata:
  name: flask-pod-secret
type: Opaque
data:
  influx_server: {{ .Values.influx_server | b64enc }}
  influx_org: {{ .Values.influx_org | b64enc }}
  influx_token: {{ .Values.influx_token | b64enc }}
  mqtt_user: {{ .Values.mqtt_user | b64enc }}
  mqtt_pass: {{ .Values.mqtt_pass | b64enc }}
  mqtt_server: {{ .Values.mqtt_server | b64enc }}
